system:
  out: console
  in: console
logging:
  out: console
  level: INFO
  file: files/logs/log.log
vk:
  keys: files/data/vk_bot_keys.json
room:
  keys: files/data/google_token.json
  schedule:
    enable: true
    spreadsheet: 1UHRZeVOl2uzEZEVQs-dpBya6FmrvyXxZwM8D1cEzg68
data:
  council: files/info/council2.json
  events: files/info/notice.json
  fired: files/fired_event.json
  texts:
    about: files/texts/about_club.txt
    projects: files/texts/projects.txt
    join: files/texts/join.txt
  database:
    auth:
      user: postgres
      password: 1234
      host: localhost
      port: 5432
      database: glados_db


