system:
  out: vk
  in: vk
logging:
  out: console
  file: files/log.log
vk:
  keys: files/vk_bot_keys.json
data:
  council: files/council.json
  events: files/notice.json
  fired: files/fired_event.json
room:
  keys: files/google_token.json
  schedule:
    enable: false
    spreadsheet: 1UHRZeVOl2uzEZEVQs-dpBya6FmrvyXxZwM8D1cEzg68
